services:
  - type: web
    name: destroyai-humanizer
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: NODE_ENV
        value: production
    region: oregon
